name: Big SBOM Test
on:
  workflow_dispatch:

permissions: {}
jobs:
  attest-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Generate image SBOM attestation
        uses: actions/attest-sbom@v2
        with:
          subject-name: "Test"
          subject-digest: "sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32"
          sbom-path: ./sbom-image.spdx.json
          push-to-registry: false 
