name: Big SBOM Test
on:
  workflow_dispatch:
    inputs:
      size:
        description: 'SBOM size in MB'
        type: string
        required: true
        default: 16
permissions: {}
jobs:
  attest-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Create SBOM
        run: |
          dd if=/dev/zero of=output.dat bs=${{ inputs.size }}M count=1
          cat output.dat | base64 > payload.dat
          jq --null-input --rawfile payload payload.dat '{"spdxVersion":"SPDX-2.3","SPDXID":"SPDXRef-DOCUMENT","payload":$payload}' > sbom.json
      
      # Run attestation 6 times with 10-second intervals
      - name: Attest SBOM - Run 1
        uses: ./
        env:
          INPUT_PRIVATE-SIGNING: 'true'
        with:
          subject-digest: 'sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32'
          subject-name: 'subject'
          sbom-path: 'sbom.json'
      
      # - name: Wait 10 seconds
      #   run: sleep 10
      
      # - name: Attest SBOM - Run 2
      #   uses: ./
      #   env:
      #     INPUT_PRIVATE-SIGNING: 'true'
      #   with:
      #     subject-digest: 'sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32'
      #     subject-name: 'subject'
      #     sbom-path: 'sbom.json'
      
      # - name: Wait 10 seconds
      #   run: sleep 10
      
      # - name: Attest SBOM - Run 3
      #   uses: ./
      #   env:
      #     INPUT_PRIVATE-SIGNING: 'true'
      #   with:
      #     subject-digest: 'sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32'
      #     subject-name: 'subject'
      #     sbom-path: 'sbom.json'
      
      # - name: Wait 10 seconds
      #   run: sleep 10
      
      # - name: Attest SBOM - Run 4
      #   uses: ./
      #   env:
      #     INPUT_PRIVATE-SIGNING: 'true'
      #   with:
      #     subject-digest: 'sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32'
      #     subject-name: 'subject'
      #     sbom-path: 'sbom.json'
      
      # - name: Wait 10 seconds
      #   run: sleep 10
      
      # - name: Attest SBOM - Run 5
      #   uses: ./
      #   env:
      #     INPUT_PRIVATE-SIGNING: 'true'
      #   with:
      #     subject-digest: 'sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32'
      #     subject-name: 'subject'
      #     sbom-path: 'sbom.json'
      
      # - name: Wait 10 seconds
      #   run: sleep 10
      
      # - name: Attest SBOM - Run 6
      #   uses: ./
      #   env:
      #     INPUT_PRIVATE-SIGNING: 'true'
        with:
          subject-digest: 'sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32'
          subject-name: 'subject'
          sbom-path: 'sbom.json'
